k8s_cluster:
  children:
    control_plane:
      hosts:
        master1:
          k8s_net_ip: 10.10.0.11
        master2:
          k8s_net_ip: 10.10.0.12
        master3:
          k8s_net_ip: 10.10.0.13
    workers:
      hosts:
        worker1:
          k8s_net_ip: 10.10.0.30
        worker2:
          k8s_net_ip: 10.10.0.31
        worker3:
          k8s_net_ip: 10.10.0.32
        worker4:
          k8s_net_ip: 10.10.0.33
