k8s_cluster:
  children:
    control_plane:
      hosts:
        master1:
          k8s_net_ip: 10.10.0.11
          k8s_interface: enp7s0
        master2:
          k8s_net_ip: 10.10.0.12
          k8s_interface: enp7s0
        master3:
          k8s_net_ip: 10.10.0.13
          k8s_interface: enp7s0
    workers:
      hosts:
        worker1:
          k8s_net_ip: 10.10.0.30
          k8s_interface: enp7s0
        worker2:
          k8s_net_ip: 10.10.0.31
          k8s_interface: enp7s0
        worker3:
          k8s_net_ip: 10.10.0.32
          k8s_interface: enp7s0
        worker4:
          k8s_net_ip: 10.10.0.33
          k8s_interface: enp7s0
