---
- name: Disable swap on the machine
  ansible.builtin.command:
    cmd: "swapoff -a"
  changed_when: false

- name: Dismount swap
  ansible.builtin.mount:
    path: "{{ swap_file_path }}"
    state: absent
