---
- name: Enable containerd
  ansible.builtin.systemd:
    name: containerd
    enabled: true
    state: started

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
